### ISSUE TITLE
Transaction Processor stops after reaching the current block

### ISSUE THREAD

**Issue by MWFIAE** [ElrondNetwork/transaction-processor#2]
Hi, 

not sure if it is intended behavior but I have seen that the transaction processing just stops after reaching the current block.
Since no event is emitted for this it is not possible to react to that (for example useful to restart the processor or handle new transactions yourself).

This makes it very difficult to use this package in a meaningful way, in my opinion. Or am I missing something essential?

Have a nice day,
Martin Wagner

**Comment by jasseem** [comment]
Hi Martin, 

For now this was the intended behaviour. I guess your expected behaviour can be done by looping over the `Start()` method of the processor. Each loop with update the processor's state by persisting it in a permanent storage.

The idea of not to natively wait and continue after reaching the current block is to give you the possibility to trigger the whole process periodically using a cloud function with a cloud scheduler for example.

I hope I've answered to the question, do not hesitate to get back to me and propose something :)

**Comment by dragos-rebegea** [comment]
Best practice if you want to process live transactions is to use cron jobs. Check the example for this [here](https://github.com/ElrondNetwork/transaction-processor/tree/main/example).
